# Generated by Django 4.2.13 on 2024-06-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorName", models.CharField(max_length=200)),
                ("qualification", models.CharField(max_length=200)),
                ("authorImage", models.FileField(upload_to="authorimage")),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("decs", models.TextField()),
                ("link", models.URLField()),
                (
                    "authorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aisapis.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventName", models.CharField(max_length=100)),
                ("eventDesc", models.TextField()),
                ("eventImage", models.FileField(upload_to="events")),
                (
                    "eventType",
                    models.CharField(
                        choices=[
                            ("NTE", "Non Technical Events"),
                            ("TE", "Technical Events"),
                            ("CDE", "Carrier Development Events"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="faqs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quesiton", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="feedBackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=150)),
                ("who", models.CharField(max_length=100)),
                ("feedback", models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name="joinAisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("prn", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=10)),
                ("cgpa", models.CharField(max_length=5)),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("vp", "Vice President"),
                            ("volunteers", "Volunteers"),
                            ("treasurer", "Treasurers"),
                            ("planning", "Planning Team"),
                            ("tech", "Technical Team"),
                            ("media", "Media Team"),
                            ("secretary", "Secretaries"),
                            ("p", "president"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[("AIML", "AIML"), ("AIDS", "AIDS")], max_length=100
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="member")),
            ],
        ),
        migrations.CreateModel(
            name="notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="noticeboard")),
            ],
        ),
        migrations.CreateModel(
            name="gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("galleryImage", models.FileField(upload_to="gallery")),
                (
                    "eventName",
                    models.ForeignKey(
                        max_length=150,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aisapis.events",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="blogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="blogImage")),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aisapis.blog"
                    ),
                ),
            ],
        ),
    ]
