# Generated by Django 4.2.13 on 2024-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aisapis", "0009_alter_events_eventtype_alter_members_branch_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="members",),
        migrations.AlterField(
            model_name="events",
            name="eventType",
            field=models.CharField(
                choices=[
                    ("NTE", "Non Technical Events"),
                    ("TE", "Technical Events"),
                    ("CDE", "Carrier Development Events"),
                ],
                max_length=200,
            ),
        ),
    ]
